// Package wsdatachannel is a client for the Logalty LGT Portal WsDataChannel
// SOAP service: sending shipments for signature, polling their state, building
// sign-in URLs and downloading the resulting documents and certificates.
//
// It is a Go port of the net.logalty.sender.lgtportal.wsDataChannel package of
// the lgtweb Java SDK, whose stubs were generated by Apache Axis 1.4. The wire
// format is SOAP 1.1, document/literal wrapped, with an empty SOAPAction.
//
// Type and field names follow the Java SDK — including its spelling of
// "Remmitance" — so that this package stays greppable against the vendor's own
// documentation and stubs.
package wsdatachannel

import (
	"encoding/xml"
	"fmt"
	"strings"
	"time"
)

// Receiver is the addressee of a shipment.
//
// Every field is optional on the wire, and empty strings are omitted from the
// request rather than sent as empty elements. Which fields are actually
// required depends on the shipment type configured for your company: an
// electronic notification needs an email, a postal one needs the street fields.
//
// The fields are declared in the order the Axis stub's type descriptor lists
// them — alphabetical, not logical — because that is the order the elements go
// out in, and the schema behind this service declares a sequence. Grouping the
// address fields more sensibly would reorder the request.
type Receiver struct {
	// ExternalID is your own identifier for the shipment, echoed back in
	// status responses so you can correlate them.
	ExternalID string `xml:"externalId,omitempty"`

	ReceiverCommentAtt       string `xml:"receiverCommentAtt,omitempty"`
	ReceiverEmail            string `xml:"receiverEmail,omitempty"`
	ReceiverIdentityID       string `xml:"receiverIdentityId,omitempty"`
	ReceiverIdentityType     string `xml:"receiverIdentityType,omitempty"`
	ReceiverLastName1        string `xml:"receiverLastName1,omitempty"`
	ReceiverLastName2        string `xml:"receiverLastName2,omitempty"`
	ReceiverMidName          string `xml:"receiverMidName,omitempty"`
	ReceiverMobile           string `xml:"receiverMobile,omitempty"`
	ReceiverName             string `xml:"receiverName,omitempty"`
	ReceiverPhone            string `xml:"receiverPhone,omitempty"`
	ReceiverStreet           string `xml:"receiverStreet,omitempty"`
	ReceiverStreetCountry    string `xml:"receiverStreetCountry,omitempty"`
	ReceiverStreetDoor       string `xml:"receiverStreetDoor,omitempty"`
	ReceiverStreetFloor      string `xml:"receiverStreetFloor,omitempty"`
	ReceiverStreetNumber     string `xml:"receiverStreetNumber,omitempty"`
	ReceiverStreetNumberType string `xml:"receiverStreetNumberType,omitempty"`
	ReceiverStreetPortal     string `xml:"receiverStreetPortal,omitempty"`
	ReceiverStreetState      string `xml:"receiverStreetState,omitempty"`
	ReceiverStreetType       string `xml:"receiverStreetType,omitempty"`
	ReceiverStreetZip        string `xml:"receiverStreetZip,omitempty"`
	ReceiverStreetZone       string `xml:"receiverStreetZone,omitempty"`

	// SignatureOrder positions this receiver in a sequential signing flow.
	// It is a pointer because order 0 and "no order at all" mean different
	// things to the portal.
	SignatureOrder *int `xml:"signatureOrder,omitempty"`
}

// BinaryContentItem is one file attached to a multi-receiver shipment. It maps
// to the XSD type "file".
type BinaryContentItem struct {
	// Type is the file extension without a dot, such as "pdf".
	Type string `xml:"type,omitempty"`
	// Name is the file name shown to the receiver.
	Name string `xml:"name,omitempty"`
	// Content is the file, base64-encoded. Use EncodeContent to fill it.
	Content string `xml:"content,omitempty"`
}

// TemplateReceiver drives a shipment built from a portal-side template. The
// twenty generic fields are substituted into the template's placeholders; what
// each one means is defined by the template, not by this SDK.
//
// The schema derives this type from receiver by extension, so a TemplateReceiver
// carries every Receiver field as well — that is where the addressee's name,
// email and identity document go. The embedded Receiver is declared first
// because extension puts the base type's elements ahead of the derived type's
// on the wire.
//
// As with Receiver, the declaration order is the Axis type descriptor's, which
// sorts the numbered fields as strings. Hence field1, field10..field19, field2,
// field20, field3 and so on: unlovely, but it is the order that goes on the
// wire.
type TemplateReceiver struct {
	Receiver

	CompanyID string `xml:"companyId,omitempty"`

	Field1  string `xml:"field1,omitempty"`
	Field10 string `xml:"field10,omitempty"`
	Field11 string `xml:"field11,omitempty"`
	Field12 string `xml:"field12,omitempty"`
	Field13 string `xml:"field13,omitempty"`
	Field14 string `xml:"field14,omitempty"`
	Field15 string `xml:"field15,omitempty"`
	Field16 string `xml:"field16,omitempty"`
	Field17 string `xml:"field17,omitempty"`
	Field18 string `xml:"field18,omitempty"`
	Field19 string `xml:"field19,omitempty"`
	Field2  string `xml:"field2,omitempty"`
	Field20 string `xml:"field20,omitempty"`
	Field3  string `xml:"field3,omitempty"`
	Field4  string `xml:"field4,omitempty"`
	Field5  string `xml:"field5,omitempty"`
	Field6  string `xml:"field6,omitempty"`
	Field7  string `xml:"field7,omitempty"`
	Field8  string `xml:"field8,omitempty"`
	Field9  string `xml:"field9,omitempty"`

	PDFFileName string `xml:"pdfFileName,omitempty"`
	TemplateID  string `xml:"templateId,omitempty"`
	TypeID      string `xml:"typeId,omitempty"`
}

// RemmitanceResult is what an asynchronous send returns: an outcome code and
// the initial state of each document created.
type RemmitanceResult struct {
	// RetCode is 0 on success. Anything else is a portal-side rejection, with
	// Message carrying the explanation.
	RetCode   int             `xml:"retCode"`
	Message   string          `xml:"message"`
	Documents []DocumentState `xml:"documents"`
}

// Err turns a non-zero RetCode into an error. The Java SDK leaves callers to
// check the code themselves; this is a convenience, not a change of behaviour,
// since the result is still returned in full.
func (r RemmitanceResult) Err() error {
	if r.RetCode == 0 {
		return nil
	}
	return fmt.Errorf("wsdatachannel: shipment rejected with code %d: %s", r.RetCode, r.Message)
}

// SRemmitanceResult is what a synchronous send returns: the URL to redirect the
// signer to straight away.
//
// The schema derives it from remmitanceResult, so it also carries RetCode,
// Message and Documents — check RetCode (or call Err) before trusting URLSaml.
type SRemmitanceResult struct {
	RemmitanceResult

	URLSaml string `xml:"urlSaml"`
}

// SMultiRemmitanceResult is the synchronous multi-receiver equivalent, with one
// URL per receiver. Like SRemmitanceResult it extends remmitanceResult, so the
// outcome fields apply here too.
type SMultiRemmitanceResult struct {
	RemmitanceResult

	Link []ReceiverURL `xml:"link"`
}

// ReceiverURL pairs a receiver identity with the URL that signs them in.
type ReceiverURL struct {
	Receiver string `xml:"receiver"`
	URL      string `xml:"url"`
}

// DocumentSamlResult is a sign-in URL built for an already-sent shipment.
type DocumentSamlResult struct {
	Receiver string `xml:"receiver"`
	Result   int    `xml:"result"`
	URL      string `xml:"url"`
}

// DocumentState is the state of one shipment. Note that the date fields are
// strings here: this operation reports them in the portal's local time with no
// offset. Use the UTC variant when you need unambiguous timestamps.
type DocumentState struct {
	GUID          string `xml:"guid,attr"`
	ID            int    `xml:"id,attr"`
	ExternalID    string `xml:"externalId,attr"`
	TypeID        int    `xml:"typeid,attr"`
	Status        int    `xml:"status,attr"`
	StatusComment string `xml:"statusComment,attr"`
	Result        int    `xml:"result,attr"`
	ResultComment string `xml:"resultComment,attr"`
	SendDate      string `xml:"sendate,attr"`
	ResultDate    string `xml:"resultdate,attr"`
	LastUpdate    string `xml:"lastupdate,attr"`
}

// DocumentStateUTC is DocumentState with real timestamps, plus the document
// itself when the portal chooses to include it.
type DocumentStateUTC struct {
	GUID          string `xml:"guid,attr"`
	ID            int    `xml:"id,attr"`
	ExternalID    string `xml:"externalId,attr"`
	TypeID        int    `xml:"typeid,attr"`
	Status        int    `xml:"status,attr"`
	StatusComment string `xml:"statusComment,attr"`
	Result        int    `xml:"result,attr"`
	ResultComment string `xml:"resultComment,attr"`
	SendDate      Time   `xml:"sendate,attr"`
	ResultDate    Time   `xml:"resultdate,attr"`
	LastUpdate    Time   `xml:"lastupdate,attr"`

	// Binary is the document, base64-encoded. Use DecodeBinary to read it.
	Binary string `xml:"binary"`
}

// DocumentStateMultiReceiver is the state of a multi-receiver shipment, broken
// down into signature groups. It extends documentState in the schema, so the
// shipment-level GUID, status and dates are present as well.
type DocumentStateMultiReceiver struct {
	DocumentState

	Groups []Group `xml:"groups"`
}

// Group is one signature group of a multi-receiver shipment.
type Group struct {
	GroupID    int         `xml:"group-id,attr"`
	Status     int         `xml:"status,attr"`
	Result     int         `xml:"result,attr"`
	Date       Time        `xml:"date,attr"`
	Signatures []Signature `xml:"signatures"`
}

// Signature is one receiver's signature within a Group.
type Signature struct {
	ReceiverID         int    `xml:"receiver-id,attr"`
	ReceiverIdentityID string `xml:"receiverIdentityId,attr"`
	RuleID             int    `xml:"rule_id,attr"`
	Status             int    `xml:"status,attr"`
	StatusCom          string `xml:"statusCom,attr"`
	Result             int    `xml:"result,attr"`
	ResultCom          string `xml:"resultCom,attr"`
	Date               Time   `xml:"date,attr"`
}

// DocumentDoc is a downloaded document or certificate.
type DocumentDoc struct {
	GUID       string `xml:"guid,attr"`
	ID         int    `xml:"id,attr"`
	ExternalID string `xml:"externalId,attr"`

	// Binary is the file, base64-encoded. Use DecodeBinary to read it.
	Binary string `xml:"binary"`
}

// DocumentExport is the result of a shipment-list export.
type DocumentExport struct {
	// Data is the export payload, base64-encoded — a CSV for the only
	// response type the portal currently offers.
	Data string `xml:"data,attr"`
	// Error is set instead of Data when the export failed.
	Error string `xml:"error,attr"`
}

// Content maps the XSD "content" type. The current operations never return it;
// it is kept because the vendor's schema declares it.
type Content struct {
	Name  string `xml:"name,attr"`
	Type  string `xml:"type,attr"`
	Value string `xml:",chardata"`
}

// Time is an xsd:dateTime as the portal writes it.
//
// It is not time.Time because the portal is inconsistent about time zones: some
// responses carry an offset and some do not. A plain time.Time field would make
// encoding/xml reject the latter outright.
type Time struct {
	time.Time
}

// dateTimeLayouts are tried in order. The offset-bearing forms come first so a
// well-formed timestamp is never misread as a local one.
//
// The space-separated layouts are not xsd:dateTime, but the portal emits them:
// shippingStatus reports dates like "2026-09-11 19:47:12.503". They are
// accepted here so that a shippingStatusUTC response in the same shape decodes
// instead of failing the whole call.
var dateTimeLayouts = []string{
	time.RFC3339Nano,
	time.RFC3339,
	"2006-01-02T15:04:05.999999999",
	"2006-01-02T15:04:05",
	"2006-01-02 15:04:05.999999999",
	"2006-01-02 15:04:05",
	"2006-01-02",
}

func (t *Time) parse(value string) error {
	value = strings.TrimSpace(value)
	if value == "" {
		t.Time = time.Time{}
		return nil
	}
	for _, layout := range dateTimeLayouts {
		if parsed, err := time.Parse(layout, value); err == nil {
			t.Time = parsed
			return nil
		}
	}
	return fmt.Errorf("wsdatachannel: cannot parse %q as a dateTime", value)
}

// UnmarshalXMLAttr decodes a dateTime carried as an attribute.
func (t *Time) UnmarshalXMLAttr(attr xml.Attr) error {
	return t.parse(attr.Value)
}

// UnmarshalXML decodes a dateTime carried as element text.
func (t *Time) UnmarshalXML(d *xml.Decoder, start xml.StartElement) error {
	var value string
	if err := d.DecodeElement(&value, &start); err != nil {
		return err
	}
	return t.parse(value)
}

// MarshalXMLAttr encodes the timestamp as xsd:dateTime, omitting the attribute
// entirely when the time is zero.
func (t Time) MarshalXMLAttr(name xml.Name) (xml.Attr, error) {
	if t.IsZero() {
		return xml.Attr{}, nil
	}
	return xml.Attr{Name: name, Value: t.Format(time.RFC3339)}, nil
}
